=== lindenis-org/lindenis-v833-package/network/snapcast/snapcast/doc/json_rpc_api/client.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "config": {
      "type": "object",
      "properties": {
        "latency": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "stream": {
          "type": "string"
        },
        "volume": {
          "type": "object",
          "properties": {
            "muted": {
              "type": "boolean"
            },
            "percent": {
              "type": "integer"
            }
          },
          "required": [
            "muted",
            "percent"
          ]
        }
      },
      "required": [
        "latency",
        "name",
        "stream",
        "volume"
      ]
    },
    "connected": {
      "type": "boolean"
    },
    "host": {
      "type": "object",
      "properties": {
        "arch": {
          "type": "string"
        },
        "ip": {
          "type": "string"
        },
        "mac": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "os": {
          "type": "string"
        }
      },
      "required": [
        "arch",
        "ip",
        "mac",
        "name",
        "os"
      ]
    },
    "lastSeen": {
      "type": "object",
      "properties": {
        "sec": {
          "type": "integer"
        },
        "usec": {
          "type": "integer"
        }
      },
      "required": [
        "sec",
        "usec"
      ]
    },
    "snapclient": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "protocolVersion": {
          "type": "integer"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "protocolVersion",
        "version"
      ]
    }
  },
  "required": [
    "config",
    "connected",
    "host",
    "lastSeen",
    "snapclient"
  ]
}

=== lindenis-org/lindenis-v833-package/network/snapcast/snapcast/doc/json_rpc_api/client.json
{
  "config": {
    "latency": 0,
    "name": "Schlafzimmer",
    "stream": "pipe:///tmp/snapfifo",
    "volume": {
      "muted": false,
      "percent": 100
    }
  },
  "connected": false,
  "host": {
    "arch": "armv6l",
    "ip": "192.168.0.24",
    "mac": "80:1f:02:ed:fd:e0",
    "name": "wohnzimmer",
    "os": "Raspbian GNU/Linux 8.0 (jessie)"
  },
  "lastSeen": {
    "sec": 1464339375,
    "usec": 480894
  },
  "snapclient": {
    "name": "Snapclient",
    "protocolVersion": 2,
    "version": "0.7.0"
  }
}
